DIRECTORY = './2019.526'
DIRECTORY_ROOMID_UID = f'{DIRECTORY}/roomid_uid'
DIRECTORY_ROOMID_UID_FOLLOWERS = f'{DIRECTORY}/roomid_uid_followers'
DIRECTORY_ROOMID_FOLLOWERS_GUARD = f'{DIRECTORY}/roomid_followers_guard'
DIRECTORY_SORTED = f'{DIRECTORY}/sorted'

LEN_CHUNCK = 10
SLEEP = 0.28
